[package]
name = "polkadot-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "2.1", default-features = false }
parity-codec-derive = { version = "2.1", default-features = false }
substrate-primitives = { git = "https://github.com/gterzian/substrate/", branch="test_protocol_rewrite_on_alexander" }
substrate-client = { git = "https://github.com/gterzian/substrate/", branch="test_protocol_rewrite_on_alexander" }
sr-version = { git = "https://github.com/gterzian/substrate/", branch="test_protocol_rewrite_on_alexander" }
sr-std = { git = "https://github.com/gterzian/substrate/", branch="test_protocol_rewrite_on_alexander" }
sr-primitives = { git = "https://github.com/gterzian/substrate/", branch="test_protocol_rewrite_on_alexander" }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/gterzian/substrate/", branch="test_protocol_rewrite_on_alexander" }
pretty_assertions = "0.4"

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"parity-codec-derive/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-version/std",
	"sr-primitives/std",
	"serde_derive",
	"serde/std",
]
