[package]
name = "polkadot-cli"
version = "0.3.9"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot node implementation in Rust."

[dependencies]
log = "0.3"
tokio = "0.1.7"
futures = "0.1.17"
exit-future = "0.1"
substrate-cli = { git = "https://github.com/gterzian/substrate/", branch="test_protocol_rewrite_on_alexander" }
polkadot-service = { path = "../service" }
structopt = "0.2.13"
